id = "pylance"
name = "Pylance"
version = "0.1.0"
schema_version = 1
authors = ["Rodney Osodo <socials@rodneyosodo.com>"]
description = "Zed plugin for Pylance https://github.com/microsoft/pylance-release"
repository = "https://github.com/0x6flab/zed-pylance"

[language_servers.pylance]
name = "Pylance Language Server"
Language = "Python"
